export { default as Home } from './Home'
export { default as Work } from './Work'
export { default as WorkStudy } from './Work/WorkStudy/WorkStudy'
export { default as Profile } from './Profile'
export { default as NoMatch } from './NoMatch'